
package com.mycompany.Fees_Management_System;

import java.awt.SplashScreen;
import javax.swing.JOptionPane;
import com.mycompany.Fees_Management_System.login;


/**
 *
 * @author ASUS
 */
public class Welcomepage extends javax.swing.JFrame {

    public Welcomepage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PB = new javax.swing.JProgressBar();
        loading_screen = new javax.swing.JLabel();
        loading_value = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PB.setBackground(new java.awt.Color(255, 255, 255));
        PB.setForeground(new java.awt.Color(0, 255, 0));
        jPanel1.add(PB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 520, 20));

        loading_screen.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        loading_screen.setForeground(new java.awt.Color(255, 255, 255));
        loading_screen.setText("Loading...");
        jPanel1.add(loading_screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 280, 30));

        loading_value.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        loading_value.setForeground(new java.awt.Color(255, 255, 255));
        loading_value.setText("%0");
        jPanel1.add(loading_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 60, 30));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/Fees_Management_System/welcome.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 540, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</e
        Welcomepage sp = new Welcomepage();
        login l = new login();
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                sp.setVisible(true);
            }
            
        });

        
        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(60);
                sp.loading_value.setText(i + "%");
                if (i == 10) {
                    sp.loading_screen.setText("Turning on Modules....");
                }
                if (i == 40) {
                    sp.loading_screen.setText("Loading Modules....");
                }
                if (i == 80) {
                    sp.loading_screen.setText("Connecting Database....");
                }
                sp.PB.setValue(i);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        new Welcomepage().setVisible(false);
        l.setVisible(true);
        sp.dispose();
    }

    /* Create and display the form */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar PB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loading_screen;
    private javax.swing.JLabel loading_value;
    // End of variables declaration//GEN-END:variables
}
